const apiPath = {
    MOVIE_LIST: "/api/QuanLyPhim/LayDanhSachPhimPhanTrang",
    ADD_MOVIE: "/api/QuanLyPhim/ThemPhimUploadHinh",
    UPDATE_MOVIE: "/api/QuanLyPhim/CapNhatPhimUpload",
    DELETE_MOVIE: "/api/QuanLyPhim/XoaPhim",
    CINEMA_LIST: "/api/QuanLyRap/LayThongTinHeThongRap",
    CINEMA_GROUP: "/api/QuanLyRap/LayThongTinCumRapTheoHeThong",
    SHOWTIME: "/api/QuanLyDatVe/TaoLichChieu",
    MOVIE_DETAIL: "/api/QuanLyPhim/LayThongTinPhim",
    USER_SIGNUP: "/api/QuanLyNguoiDung/DangKy",
    PROFILE: "/api/QuanLyNguoiDung/DangNhap",
    PROFILE_ACTIONS: "/api/QuanLyNguoiDung/ThongTinTaiKhoan",
    USER_LIST: "/api/QuanLyNguoiDung/LayDanhSachNguoiDungPhanTrang",
    DELETE_USER: "/api/QuanLyNguoiDung/XoaNguoiDung",
    TYPE_USER: "/api/QuanLyNguoiDung/LayDanhSachLoaiNguoiDung",
    ADD_USER: "/api/QuanLyNguoiDung/ThemNguoiDung",
    SEARCH_USER_LIST: "/api/QuanLyNguoiDung/LayDanhSachNguoiDung",
    UPDATE_USER: "/api/QuanLyNguoiDung/CapNhatThongTinNguoiDung",
};
export default apiPath;